openapi: 3.0.3
info:
  title: DataSpray Ingest API
  description: DataSpray Ingest API documentation for clients ingesting data.
  version: 1.0.0

servers:
  - url: https://api.dataspray.io

security:
  - Authorizer: [ ]

components:
  securitySchemes:
    Authorizer:
      type: apiKey
      in: header
      name: Authorization

paths:
  /ping:
    $ref: 'paths-health.yaml#/~1ping'
  /account/{accountId}/target/{targetId}/message:
    $ref: 'paths-ingest.yaml#/~1account~1{accountId}~1target~1{targetId}~1message'