# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from dataspray.models.read_directory_response_files_inner import ReadDirectoryResponseFilesInner


class ReadDirectoryResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ReadDirectoryResponse - a model defined in OpenAPI

        files: The files of this ReadDirectoryResponse.
    """

    files: List[ReadDirectoryResponseFilesInner] = Field(alias="files")

ReadDirectoryResponse.update_forward_refs()
