# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ReadDirectoryResponseFilesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ReadDirectoryResponseFilesInner - a model defined in OpenAPI

        name: The name of this ReadDirectoryResponseFilesInner.
        is_dir: The is_dir of this ReadDirectoryResponseFilesInner.
        is_symbolic: The is_symbolic of this ReadDirectoryResponseFilesInner.
    """

    name: str = Field(alias="name")
    is_dir: bool = Field(alias="isDir")
    is_symbolic: bool = Field(alias="isSymbolic")

ReadDirectoryResponseFilesInner.update_forward_refs()
