# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class StatResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    StatResponse - a model defined in OpenAPI

        ctime_in_ms_epoch: The ctime_in_ms_epoch of this StatResponse [Optional].
        mtime_in_ms_epoch: The mtime_in_ms_epoch of this StatResponse [Optional].
        is_readonly: The is_readonly of this StatResponse.
        size_in_bytes: The size_in_bytes of this StatResponse [Optional].
        is_dir: The is_dir of this StatResponse.
        is_symbolic: The is_symbolic of this StatResponse.
    """

    ctime_in_ms_epoch: Optional[int] = Field(alias="ctimeInMsEpoch", default=None)
    mtime_in_ms_epoch: Optional[int] = Field(alias="mtimeInMsEpoch", default=None)
    is_readonly: bool = Field(alias="isReadonly")
    size_in_bytes: Optional[int] = Field(alias="sizeInBytes", default=None)
    is_dir: bool = Field(alias="isDir")
    is_symbolic: bool = Field(alias="isSymbolic")

StatResponse.update_forward_refs()
