# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class WatcherEvent(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    WatcherEvent - a model defined in OpenAPI

        type: The type of this WatcherEvent.
        uri: The uri of this WatcherEvent.
    """

    type: str = Field(alias="type")
    uri: str = Field(alias="uri")

WatcherEvent.update_forward_refs()
