# coding: utf-8

"""
    DataSpray DevEnvLambda API

    ClearFlask API documentation.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI
from mangum import Mangum

from dataspray.apis.admin_api import router as AdminApiRouter
from dataspray.apis.file_system_api import router as FileSystemApiRouter
from dataspray.apis.terminal_api import router as TerminalApiRouter

app = FastAPI(
    title="DataSpray DevEnvLambda API",
    description="ClearFlask API documentation.",
    version="1.0.0",
)

app.include_router(AdminApiRouter)
app.include_router(FileSystemApiRouter)
app.include_router(TerminalApiRouter)

handler = Mangum(app, lifespan="off")
