openapi: 3.0.3
info:
  title: DataSpray Ingest API
  description: DataSpray Ingest API documentation for clients ingesting data.
  version: 1.0.0

servers:
  - url: https://api.dataspray.io

components:
  securitySchemes:
    Authorizer:
      $ref: 'common.yaml#/components/securitySchemes/Authorizer'

# Use Lambda Authorizer by default unless overriden by specific endpoint
security:
  - Authorizer: [ ]

paths:
  /ping:
    $ref: 'paths-health.yaml#/~1ping'
  /organization/{organizationName}/target/{targetId}/message:
    $ref: 'paths-ingest.yaml#/~1organization~1{organizationName}~1target~1{targetId}~1message'
