openapi: 3.0.3
info:
  title: DataSpray Ingest API
  description: DataSpray Ingest API documentation for clients ingesting data.
  version: 1.0.0

servers:
  - url: https://api.dataspray.io

security:
  - Authorizer: [ ]

components:
  securitySchemes:
    Authorizer:
      # WARNING: If changed, also change in api.yaml
      # This cannot be a reference such as "$ref: 'common.yaml#/components/securitySchemes/Authorizer'"
      # because generator will only use 'type' and 'scheme' fields for some weird reason.
      type: http
      in: header
      name: Authorization
      scheme: apikey

paths:
  /ping:
    $ref: 'paths-health.yaml#/~1ping'
  /organization/{organizationName}/target/{targetId}/message:
    $ref: 'paths-ingest.yaml#/~1organization~1{organizationName}~1target~1{targetId}~1message'
