/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray DevEnvLambda API
 * ClearFlask API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadDirectoryResponseFilesInner } from './ReadDirectoryResponseFilesInner';
import {
    ReadDirectoryResponseFilesInnerFromJSON,
    ReadDirectoryResponseFilesInnerFromJSONTyped,
    ReadDirectoryResponseFilesInnerToJSON,
} from './ReadDirectoryResponseFilesInner';

/**
 * 
 * @export
 * @interface ReadDirectoryResponse
 */
export interface ReadDirectoryResponse {
    /**
     * 
     * @type {Array<ReadDirectoryResponseFilesInner>}
     * @memberof ReadDirectoryResponse
     */
    files: Array<ReadDirectoryResponseFilesInner>;
}

/**
 * Check if a given object implements the ReadDirectoryResponse interface.
 */
export function instanceOfReadDirectoryResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "files" in value;

    return isInstance;
}

export function ReadDirectoryResponseFromJSON(json: any): ReadDirectoryResponse {
    return ReadDirectoryResponseFromJSONTyped(json, false);
}

export function ReadDirectoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadDirectoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'files': ((json['files'] as Array<any>).map(ReadDirectoryResponseFilesInnerFromJSON)),
    };
}

export function ReadDirectoryResponseToJSON(value?: ReadDirectoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'files': ((value.files as Array<any>).map(ReadDirectoryResponseFilesInnerToJSON)),
    };
}

