/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray DevEnvLambda API
 * ClearFlask API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadDirectoryResponseFilesInner
 */
export interface ReadDirectoryResponseFilesInner {
    /**
     * 
     * @type {string}
     * @memberof ReadDirectoryResponseFilesInner
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReadDirectoryResponseFilesInner
     */
    isDir: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReadDirectoryResponseFilesInner
     */
    isSymbolic: boolean;
}

/**
 * Check if a given object implements the ReadDirectoryResponseFilesInner interface.
 */
export function instanceOfReadDirectoryResponseFilesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "isDir" in value;
    isInstance = isInstance && "isSymbolic" in value;

    return isInstance;
}

export function ReadDirectoryResponseFilesInnerFromJSON(json: any): ReadDirectoryResponseFilesInner {
    return ReadDirectoryResponseFilesInnerFromJSONTyped(json, false);
}

export function ReadDirectoryResponseFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadDirectoryResponseFilesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isDir': json['isDir'],
        'isSymbolic': json['isSymbolic'],
    };
}

export function ReadDirectoryResponseFilesInnerToJSON(value?: ReadDirectoryResponseFilesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'isDir': value.isDir,
        'isSymbolic': value.isSymbolic,
    };
}

