/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray DevEnvLambda API
 * ClearFlask API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatResponse
 */
export interface StatResponse {
    /**
     * 
     * @type {number}
     * @memberof StatResponse
     */
    ctimeInMsEpoch?: number;
    /**
     * 
     * @type {number}
     * @memberof StatResponse
     */
    mtimeInMsEpoch?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StatResponse
     */
    isReadonly: boolean;
    /**
     * 
     * @type {number}
     * @memberof StatResponse
     */
    sizeInBytes?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StatResponse
     */
    isDir: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StatResponse
     */
    isSymbolic: boolean;
}

/**
 * Check if a given object implements the StatResponse interface.
 */
export function instanceOfStatResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isReadonly" in value;
    isInstance = isInstance && "isDir" in value;
    isInstance = isInstance && "isSymbolic" in value;

    return isInstance;
}

export function StatResponseFromJSON(json: any): StatResponse {
    return StatResponseFromJSONTyped(json, false);
}

export function StatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ctimeInMsEpoch': !exists(json, 'ctimeInMsEpoch') ? undefined : json['ctimeInMsEpoch'],
        'mtimeInMsEpoch': !exists(json, 'mtimeInMsEpoch') ? undefined : json['mtimeInMsEpoch'],
        'isReadonly': json['isReadonly'],
        'sizeInBytes': !exists(json, 'sizeInBytes') ? undefined : json['sizeInBytes'],
        'isDir': json['isDir'],
        'isSymbolic': json['isSymbolic'],
    };
}

export function StatResponseToJSON(value?: StatResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ctimeInMsEpoch': value.ctimeInMsEpoch,
        'mtimeInMsEpoch': value.mtimeInMsEpoch,
        'isReadonly': value.isReadonly,
        'sizeInBytes': value.sizeInBytes,
        'isDir': value.isDir,
        'isSymbolic': value.isSymbolic,
    };
}

