/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray DevEnvLambda API
 * ClearFlask API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WatcherEvent
 */
export interface WatcherEvent {
    /**
     * 
     * @type {string}
     * @memberof WatcherEvent
     */
    type: WatcherEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WatcherEvent
     */
    uri: string;
}


/**
 * @export
 */
export const WatcherEventTypeEnum = {
    CHANGED: 'CHANGED',
    CREATED: 'CREATED',
    DELETED: 'DELETED'
} as const;
export type WatcherEventTypeEnum = typeof WatcherEventTypeEnum[keyof typeof WatcherEventTypeEnum];


/**
 * Check if a given object implements the WatcherEvent interface.
 */
export function instanceOfWatcherEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "uri" in value;

    return isInstance;
}

export function WatcherEventFromJSON(json: any): WatcherEvent {
    return WatcherEventFromJSONTyped(json, false);
}

export function WatcherEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WatcherEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'uri': json['uri'],
    };
}

export function WatcherEventToJSON(value?: WatcherEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'uri': value.uri,
    };
}

