name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      lambdaRuntime:
        type: choice
        description: 'Lambda Runtime'
        required: true
        default: 'jvm'
        options:
          - jvm
          - native

jobs:
  build:
    # Skip test if this is a release commit
    # Run test if this is a push to master and deploy has been skipped
    if: "!contains(github.event.head_commit.message, '[release]') && (github.event_name != 'push' || contains(github.event.head_commit.message, '[skip deploy]'))"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 21
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget scour ghostscript fuse
          wget -nv -O /usr/local/bin/convert https://github.com/ImageMagick/ImageMagick/releases/download/7.1.1-26/ImageMagick--clang-x86_64.AppImage
          chmod a+x /usr/local/bin/convert
          convert -version
          scour --version

      # Test entire project
      - name: Maven build
        timeout-minutes: 30
        run: make action-test-${{ github.event.inputs.lambdaRuntime || 'jvm' }}
