name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Skip test if this is a release commit
    # Run test if this is a push to master and deploy has been skipped
    if: "!contains(github.event.head_commit.message, '[release]') && (github.event_name != 'push' || contains(github.event.head_commit.message, '[skip deploy]'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick scour ghostscript
          convert -version
          scour --version
      - name: Maven build
        timeout-minutes: 30
        run: mvn -B install
