name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[release]')"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick scour ghostscript
          convert -version
          scour --version
      - name: Maven build
        timeout-minutes: 30
        run: mvn -T 5 clean install
